name: Build & Release
on: [push]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    permissions:
      id-token: "write"
      contents: "read"

    env:
      DENO_AUTH_TOKENS: ${{ secrets.GH_CUSTOM_TOKEN }}@raw.githubusercontent.com

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: "npm"

      - run: npm install
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_PACKAGE_READ_TOKEN }}

      - run: npm run build
        env:
          GIT_SHA: ${{ github.sha }}
          API_VERSION: ${{ github.run_id }}

      - run: npm run lint

      - uses: zuplo/deploy-zup-action@main
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          project: zuplo-echo-api
          account_id: 4f59a390b9f139a4a82b757edd3c71dd
          api_token: ${{ secrets.ZUPLO_CF_API_TOKEN }}
